Add support for mixed train and eval datasets; set hyperparams in command line
(1) Added support for mixing old with new datasets for training and/or eval. NOTE: this is still buggy:
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`label` in this case) have excessive nesting (inputs type `list` where type `int` is expected).

(2) Added Typer support so we can easily tweak hyperparams using command-line options/arguments.